{
    'name': 'Localiza Bodega Operativa V3',
    'version': '19.0.3.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Bodega operativa, formularios, asignaciones, GPS, puestos y panel principal.',
    'description': 'Modulo unico V3 para control operativo de bodega Localiza: puestos, articulos, asignaciones, formularios operativos, reportes imprimibles y panel principal.',
    'author': 'XIM / Localiza',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'stock', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/menu_views.xml',
        'views/dashboard_views.xml',
        'views/puesto_views.xml',
        'views/articulo_views.xml',
        'views/asignacion_views.xml',
        'views/formulario_views.xml',
        'report/formulario_report.xml',
        'report/asignacion_report.xml',
    ],
    'installable': True,
    'application': True,
}
